// <auto-generated />
using Library.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.Persistance.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20240602144824_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsId")
                        .HasColumnType("int");

                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.HasKey("AuthorsId", "BooksId");

                    b.HasIndex("BooksId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 1
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 2
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 3
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 4
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 5
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 6
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 7
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 8
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 9
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 10
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 11
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 12
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 13
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 14
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 15
                        },
                        new
                        {
                            AuthorsId = 1,
                            BooksId = 16
                        },
                        new
                        {
                            AuthorsId = 2,
                            BooksId = 17
                        },
                        new
                        {
                            AuthorsId = 3,
                            BooksId = 18
                        },
                        new
                        {
                            AuthorsId = 4,
                            BooksId = 19
                        },
                        new
                        {
                            AuthorsId = 5,
                            BooksId = 20
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "johndoe@example.com",
                            Name = "John Doe",
                            Phone = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "janesmith@example.com",
                            Name = "Jane Smith",
                            Phone = "234-567-8901"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alicejohnson@example.com",
                            Name = "Alice Johnson",
                            Phone = "345-678-9012"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bobbrown@example.com",
                            Name = "Bob Brown",
                            Phone = "456-789-0123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "charliedavis@example.com",
                            Name = "Charlie Davis",
                            Phone = "567-890-1234"
                        });
                });

            modelBuilder.Entity("Library.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("NumberOfPages")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ISBN = "978-3-16-148410-0",
                            Language = "English",
                            NumberOfPages = (short)320,
                            Title = "Book One"
                        },
                        new
                        {
                            Id = 2,
                            ISBN = "978-1-56619-909-4",
                            Language = "Spanish",
                            NumberOfPages = (short)250,
                            Title = "Book Two"
                        },
                        new
                        {
                            Id = 3,
                            ISBN = "978-0-12345-678-9",
                            Language = "French",
                            NumberOfPages = (short)150,
                            Title = "Book Three"
                        },
                        new
                        {
                            Id = 4,
                            ISBN = "978-0-54321-987-6",
                            Language = "German",
                            NumberOfPages = (short)450,
                            Title = "Book Four"
                        },
                        new
                        {
                            Id = 5,
                            ISBN = "978-1-23456-789-0",
                            Language = "English",
                            NumberOfPages = (short)200,
                            Title = "Book Five"
                        },
                        new
                        {
                            Id = 6,
                            ISBN = "978-1-11111-222-2",
                            Language = "Spanish",
                            NumberOfPages = (short)180,
                            Title = "Book Six"
                        },
                        new
                        {
                            Id = 7,
                            ISBN = "978-2-22222-333-3",
                            Language = "French",
                            NumberOfPages = (short)220,
                            Title = "Book Seven"
                        },
                        new
                        {
                            Id = 8,
                            ISBN = "978-3-33333-444-4",
                            Language = "German",
                            NumberOfPages = (short)300,
                            Title = "Book Eight"
                        },
                        new
                        {
                            Id = 9,
                            ISBN = "978-4-44444-555-5",
                            Language = "English",
                            NumberOfPages = (short)320,
                            Title = "Book Nine"
                        },
                        new
                        {
                            Id = 10,
                            ISBN = "978-5-55555-666-6",
                            Language = "Spanish",
                            NumberOfPages = (short)400,
                            Title = "Book Ten"
                        },
                        new
                        {
                            Id = 11,
                            ISBN = "978-6-66666-777-7",
                            Language = "French",
                            NumberOfPages = (short)150,
                            Title = "Book Eleven"
                        },
                        new
                        {
                            Id = 12,
                            ISBN = "978-7-77777-888-8",
                            Language = "German",
                            NumberOfPages = (short)450,
                            Title = "Book Twelve"
                        },
                        new
                        {
                            Id = 13,
                            ISBN = "978-8-88888-999-9",
                            Language = "English",
                            NumberOfPages = (short)200,
                            Title = "Book Thirteen"
                        },
                        new
                        {
                            Id = 14,
                            ISBN = "978-9-99999-000-0",
                            Language = "Spanish",
                            NumberOfPages = (short)180,
                            Title = "Book Fourteen"
                        },
                        new
                        {
                            Id = 15,
                            ISBN = "978-1-01010-101-1",
                            Language = "French",
                            NumberOfPages = (short)220,
                            Title = "Book Fifteen"
                        },
                        new
                        {
                            Id = 16,
                            ISBN = "978-2-02020-202-2",
                            Language = "German",
                            NumberOfPages = (short)300,
                            Title = "Book Sixteen"
                        },
                        new
                        {
                            Id = 17,
                            ISBN = "978-3-03030-303-3",
                            Language = "English",
                            NumberOfPages = (short)320,
                            Title = "Book Seventeen"
                        },
                        new
                        {
                            Id = 18,
                            ISBN = "978-4-04040-404-4",
                            Language = "Spanish",
                            NumberOfPages = (short)400,
                            Title = "Book Eighteen"
                        },
                        new
                        {
                            Id = 19,
                            ISBN = "978-5-05050-505-5",
                            Language = "French",
                            NumberOfPages = (short)150,
                            Title = "Book Nineteen"
                        },
                        new
                        {
                            Id = 20,
                            ISBN = "978-6-06060-606-6",
                            Language = "German",
                            NumberOfPages = (short)450,
                            Title = "Book Twenty"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Library.Domain.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
